name: Build Containers

on: [push]

jobs:
  ROOT5:
    if: github.repository_owner == 'star-bnl'
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebuild up to base-stage
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-root5-base
          file: docker/Dockerfile.root5
          target: base-stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-root5-base:${{ steps.branch-name.outputs.current_branch }}_latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-root5-base,mode=max

      - name: Build release container
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-root5-base
          file: docker/Dockerfile.root5
          target: build-stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-root5-build:${{ steps.branch-name.outputs.tag }}

  ROOT6:
    if: github.repository_owner == 'star-bnl'
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebuild up to base-stage
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-root6-base
          file: docker/Dockerfile.root6
          target: base-stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-root6-base:${{ steps.branch-name.outputs.current_branch }}_latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-root6-base,mode=max

      - name: Build release container
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-root6-base
          file: docker/Dockerfile.root6
          target: build-stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-root6-build:${{ steps.branch-name.outputs.tag }}
