name: Build Containers

on:
  push:
    branches:
      - main
      - 'SL*'
    tags:
      - '*'

jobs:
  build:
    if: github.repository_owner == 'star-bnl'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starenv: [root5, root6]
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build latest container for the branch
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:cache
          cache-to:   type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:cache,mode=max
          build-args: starenv=${{ matrix.starenv }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:${{ steps.branch-name.outputs.current_branch }}_latest

      - name: Build release container
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:cache
          build-args: starenv=${{ matrix.starenv }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-build:${{ steps.branch-name.outputs.tag }}
