name: Build Containers

on:
  push:
    branches:
      - main
      - 'SL*'
    tags:
      - '*'

jobs:
  build:
    if: github.repository_owner == 'star-bnl'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starenv: [root5, root6]
        compiler: [gcc485, gcc11]
    env:
      STARENV: ${{ matrix.starenv }}-${{ matrix.compiler }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a release container
        uses: docker/build-push-action@v3
        with:
          build-args: |
            starenv=${{ matrix.starenv }}
            compiler=${{ matrix.compiler }}
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw:${{ steps.branch-name.outputs.current_branch }}-${{ env.STARENV }}

      - name: Push container image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/star-sw:${{ steps.branch-name.outputs.current_branch }}-${{ env.STARENV }}

  build-cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: .github/workflows/delete_untagged.py ${{ secrets.STAR_BNL_STAR_SW_TOKEN }}
