name: CI Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starenv: [root5, root616]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10000000

      - name: Build with Docker
        uses: docker/build-push-action@v3
        with:
          build-args: starenv=${{ matrix.starenv }}
          tags: ghcr.io/star-bnl/star-sw-${{ matrix.starenv }}-build
          outputs: type=docker,dest=/tmp/star-sw-${{ matrix.starenv }}-build.tar

      - name: Save built image for test jobs
        uses: actions/upload-artifact@v3
        with:
          name: star-sw-${{ matrix.starenv }}-build
          path: /tmp/star-sw-${{ matrix.starenv }}-build.tar

  ROOT5_test_setup:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-output name=matrix::" $(cat tests/joblist_ci.json)
        id: set-matrix

  ROOT5_test:
    runs-on: ubuntu-latest
    needs: ROOT5_test_setup
    strategy:
      matrix:
        test_id: ${{ fromJSON(needs.ROOT5_test_setup.outputs.matrix) }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star ghcr.io/star-bnl/star-test-data:v2
      - run: |
             TEST_CMD=$(docker run --rm ghcr.io/star-bnl/star-sw-root5-build star-sw/tests/executest.py -c ${{ matrix.test_id }})
             # Workaround https://sft.its.cern.ch/jira/browse/ROOT-7660 in ROOT 5 by checking the output log
             docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build \
               sh -c "set -e; MALLOC_CHECK_=3 $TEST_CMD 2>&1 | tee log; grep 'Run completed' log"

  ROOT6_test_ignore_fail:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        test_id: [50, 52, 54, 90, 91, 92, 119, 120]
        experimental: [true]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: star-sw-root616-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root616-build.tar
      - run: docker run --name star-test-data --volume /star ghcr.io/star-bnl/star-test-data:v2
      - run: |
             TEST_CMD=$(docker run --rm ghcr.io/star-bnl/star-sw-root616-build star-sw/tests/executest.py -c ${{ matrix.test_id }})
             docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root616-build sh -c "MALLOC_CHECK_=3 $TEST_CMD || echo 'Failed with an exit code: '\$?"
