name: CI Build

on: [pull_request]

jobs:
  ROOT5:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/star-bnl/star-sw-root5-base@sha256:bc73379c552ff02181d9c6778ff64bece4f11c5a2aaf75fd23cd62d9af6b8349
          push: false
          tags: ghcr.io/star-bnl/star-sw-root5-build
          file: docker/Dockerfile.root5
          outputs: type=docker,dest=/tmp/star-sw-root5-build.tar

      - name: Save built image for test jobs
        uses: actions/upload-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp/star-sw-root5-build.tar

  ROOT6:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/star-bnl/star-sw-root6-base@sha256:9b40544fa0af6ac911eddeaa396b04bab5e78da0ebef36170e779269c177e9f9
          push: false
          tags: ghcr.io/star-bnl/star-sw-root6-build
          file: docker/Dockerfile.root6

  ROOT5_test_job22:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "DbV20080712,pp2008,ITTF,OSpaceZ2,OGridLeak3D,beamLine", "/star-test-data/quick/st_physics_9043046_raw_2030002.daq")'

  ROOT5_test_job87:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "pp2017,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")'

  ROOT5_test_job88:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "pp2017,StiCA,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")'

  ROOT5_test_job89:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "pp2017,Sti,hitreuseon,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")'

  ROOT5_test_job101:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "P2018a,Sti,btof,mtd,PicoVtxDefault,BEmcChkStat,QAalltrigs,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_19136012_raw_1000016.daq")'

  ROOT5_test_job102:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "P2018a,StiCA,btof,mtd,PicoVtxDefault,BEmcChkStat,QAalltrigs,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_19136012_raw_1000016.daq")'

  ROOT5_test_job103:
    runs-on: ubuntu-latest
    needs: ROOT5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: star-sw-root5-build
          path: /tmp

      - run: docker load --input /tmp/star-sw-root5-build.tar
      - run: docker run --name star-test-data --volume /star-test-data ghcr.io/star-bnl/star-test-data
      - run: docker run --volumes-from star-test-data ghcr.io/star-bnl/star-sw-root5-build root4star -b -l -q 'bfc.C(10, "P2018a,Sti,hitreuseon,btof,mtd,PicoVtxDefault,BEmcChkStat,QAalltrigs,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_19136012_raw_1000016.daq")'
